feat: Add User's lecture API
de-alone/dokkang-server pull request #14
Opened 2022-10-28 05:34 UTC by Nam-gu

## Things to be changed

- Read User’s Lecture List API 추가
- Update User’s Lecture List API 추가
- Get All Lectures API 추가

2022-10-28 13:56 UTC, cosmoquester commented on src/main/java/com/de_alone/dokkang/controllers/LectureController.java
> +@RequestMapping("/lecture")
```suggestion
@RequestMapping("/lectures")
```
모든 강의 목록 가져오는 endpoint는 lectures (lecture + GET method는 특정 lecture 하나를 가져올 때)

2022-10-28 14:05 UTC, cosmoquester requested changes
굳굳! 👍 코멘트 몇 개만 확인해주세요!

2022-10-28 14:05 UTC, cosmoquester commented on src/main/java/com/de_alone/dokkang/security/WebSecurityConfig.java
> +        .antMatchers("/user/**").permitAll()
이 apis들은 인증된 사용자들만 요청할 수 있도록 하는 게 좋을 거 같아서 빼서 authorization을 하도록 하는 게 좋을 것 같아요!

2022-10-28 14:52 UTC, cosmoquester commented on src/main/java/com/de_alone/dokkang/payload/request/UpdateLectureRequest.java
> +    private List<Long> lecture_id;
```suggestion
    private List<Long> lecture_ids;
```
스펙상?

2022-10-28 14:53 UTC, cosmoquester commented on src/main/java/com/de_alone/dokkang/controllers/UserController.java
> +    public ResponseEntity<?> getUserLectures(@RequestParam(required = false) String jwt, @PathVariable Long user_id, @Valid @RequestBody UpdateLectureRequest updateLectureRequest) {
```suggestion
    public ResponseEntity<?> updateUserLectures(@RequestParam(required = false) String jwt, @PathVariable Long user_id, @Valid @RequestBody UpdateLectureRequest updateLectureRequest) {
```
method 이름이 겹치네요!

2022-10-28 14:54 UTC, cosmoquester commented
말고는 api들 전부 정상동작 확인했습니다!

2022-10-28 18:25 UTC, Nam-gu commented on src/main/java/com/de_alone/dokkang/payload/request/UpdateLectureRequest.java
> +    private List<Long> lecture_id;
UserController에서 lecture_ids가져오는 부분도 getLecture_ids로 바꿔서 커밋했습니다

2022-10-29 08:37 UTC, cosmoquester approved these changes
👍

2022-10-29 09:24 UTC, merged

2022-10-29 09:28 UTC, lim-it-ing commented
LGTM to me